
services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fake_restaurant_db
    ports:
      - '5432:5432'
    volumes:
      - ../Database/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - ../Database/pgadmin_data:/var/lib/pgadmin
  
  backend:
    build: ../Backend 
    container_name: fake_restaurant_server
    ports:
      - '3000:3000' 
    environment:
      DB_CONNECTION_URI: "postgres://admin:admin@db:5432/fake_restaurant_db"
      DIALECT: "postgres"
      TOKEN_SECRET: "V3RY_S3CR37_T0K3N"
    #volumes:
    #  - ../Backend:/app # Monta la directory del tuo backend nel container per sviluppo
    #  - /app/node_modules # Evita di sovrascrivere i moduli installati nel container
    depends_on:
      - db
    command: "npm start" # Comando per avviare la tua applicazione Node.js


volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

